### ISSUE TITLE
PID Loop additions

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-pid-controller#1]
Hi,

I was having a look at the PID loop and was wondering if we can add a few items as described on the Software Spec:
- choose direct or inverse (heating or cooling, unless you thought it can be done through the Kp value + or -)
- Is the "actual temperature" input the direct link connection on the front?
- recalculation time (time at which the output changes based on inputs). How is this defined at the moment?
- Fire Interlock (if zero it will set all outputs to zero)

The PID output value also seems to go to negative values?  I have connected an Inject block to change the setpoint and added the Return Temp to feed the actual Temperature value. All Kp, Ki, Kd are set to default.  In order to send a cooling valve signal we need this to be positive or have another module that will change the value to positive.

**Comment by hardillb** [comment]
closed by #2
