### ISSUE TITLE
PID loop controller operation

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-pid-controller#6]
I have been having a think about the operation of the pid controller, and I believe we need to add and modify a few things:
- we need to add a min and a max operation for the loop.  This can be achieved by stopping the calculation when the output reaches the maximum output value. When the variable then changes, the value can go down straight from the maximum point and the calculation continues.  The time between maximum and counting down can then be adjusted (differential) so the operation continues with no time holes.  We can leave the the calculation time to be set by the sensor polling time as we discussed.  
- Add an enable and disable function so a fixed value can be set on the output given the the circumstances.

There is an idea on how to implement and improve a basic PID at: 
http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/

There is an implementation of an advanced PID at:
https://github.com/wilberforce/pid-controller/

Please let me know your thoughts based on how the current PID works so we can agree to a solution.

**Comment by hardillb** [comment]
I've checked in some changes that should cover these, please test them and let me know

**Comment by davidoc85** [comment]
Scenario:
SP = 21
Temp = 19 (plant has not kicked in yet so temp can take 10min before it changes)
PID loop output starts at: 19.2
Temp = 19 (as the 10min time has not elapsed yet so no hot water in coil)
PID loop output: 66 (after 1min)
Temp = 19 (as the 10min time has not elapsed yet so no hot water in coil)
PID loop output: 66 (after 2min)
Temp = 19 (as the 10min time has not elapsed yet so no hot water in coil)
PID loop output: 66 (after 3min)
Temp = 19 (as the 10min time has not elapsed yet so no hot water in coil)
PID loop output: 66 (after 4min)
Temp = 19 (as the 10min time has not elapsed yet so no hot water in coil)
PID loop output: 66 (after 5min)

The limit is in, however it has not reached 100 in this scenario, which is what is expected after a certain time where there is no temperature change.  Once the temperature starts to rise, then the output will decrease accordingly and can hover over a certain percentage until SP "is met".

**Comment by hardillb** [comment]
I'm not seeing that behaviour

What Kp,Ki,Kd values do you have set? If you give me those I can can plug them into the test flow I have here and see what happens.

**Comment by davidoc85** [comment]
Kp=5
Ki=0.5
Kd=0
DB=0.25

**Comment by hardillb** [comment]
ok, with those starting values I'm seeing the same. No idea why at the moment

**Comment by hardillb** [comment]
I implemented the limiting for the output based on this:
http://brettbeauregard.com/blog/2011/04/improving-the-beginner%e2%80%99s-pid-reset-windup/

With that code and a Ki value less than 1 I can't see how you can ever reach 100%

**Comment by davidoc85** [comment]
Ok, I will test a bit more with more values to see what happens. I thought the windup was to limit the outputs to i.e max=100 and min=0.  But because the time is involved, this could be why.  So how is it being limited at the moment?  Is it because the calculation is giving the output limit?  It would be good to check this.  Let me know the calculation output while debugging the code and I will dig a bit more into the min and max limit.
- On another note, the "fixed topic" you have added works ok, however because the temperature is polling every 30 seconds the values can change after 30s to calculate again.  Can we add a topic to Enable PID or Disable PID based on true or false?

**Comment by davidoc85** [comment]
After testing with Kp=10 and Ki=0.8 the output went to 100 and stayed there.  

According to the logic of the addition, should this be right?  I am just thinking of how the current PID loops work that we have in our BMS controllers.

**Comment by hardillb** [comment]
The logic for the calculation starts here:
https://github.com/tyrrellsystems/node-red-contrib-pid-controller/blob/master/pid.js#L102

The integral is capped at 100 (following the example in the link) starting at https://github.com/tyrrellsystems/node-red-contrib-pid-controller/blob/master/pid.js#L126 to line 136 and then the output is also capped after being calculated here https://github.com/tyrrellsystems/node-red-contrib-pid-controller/blob/master/pid.js#L143

**Comment by hardillb** [comment]
I'm just about to push a fix for the Fixed Topic value being overwritten

**Comment by davidoc85** [comment]
Are you going to allow a Boolean value to enable/disable?  Then the desired value can be set for the loop or just default to 0.

**Comment by davidoc85** [comment]
Can't update to the latest PID, it brings out an error saying:

> if failed to parse package .json.  Tell the package author to fix package.json file. JSON.parse

@
[npm-debug - Copy.txt](https://github.com/tyrrellsystems/node-red-contrib-pid-controller/files/561663/npm-debug.-.Copy.txt)

**Comment by hardillb** [comment]
fixed the package.json

**Comment by davidoc85** [comment]
Tested this as follows:

[export.txt](https://github.com/tyrrellsystems/node-red-contrib-pid-controller/files/578311/export.txt)

However when the temperature changes the PID loop keeps on counting and calculating.  What is to be expected?

**Comment by hardillb** [comment]
I don't understand what you mean in that last question. The code only runs on an incoming message

**Comment by davidoc85** [comment]
What I mean is that I am getting a boolean value that should enable and disable the PID loop:
I am adding a fixed/1 topic and changing true or false with a fixed value.
true = 999
false = 0
However it only affects the PID loop once and then because the temperature is polling, the values continue to update.  See example:

[PIDloop fixed value.txt](https://github.com/tyrrellsystems/node-red-contrib-pid-controller/files/595748/PIDloop.fixed.value.txt)

**Comment by hardillb** [comment]
OK, I think I understand the problem. You are trying to do 2 things at once which is wrong.

If you send a message with a topic of "fixed/1" with a number you will change the value used when fixed is enabled. Changing this value does NOT enable fixed state.

To enable fixed state you need to send a message with payload of true and to disable you need to send a value of false.

**Comment by davidoc85** [comment]
After a lot of testing I came with the following issues with the PID:
- When I enable/disable by sending a true/false value to the PID the heat goes to 100 and cool to 0, then the PID resumes as normal after receiving a temperature value, although it shouldn't do as the flag's last value should still be "disabled".  Same thing is happening when I trigger fire input. 

`18/11/2016, 18:34:20Enable msg.payload : booleanfalse`
`18/11/2016, 18:34:20FireInput/0 : msg.payload : booleanfalse`
`18/11/2016, 18:34:34Temptemperature : msg.payload : number23.03`
`18/11/2016, 18:34:34PIDHeat msg.payload : number100`
`18/11/2016, 18:34:34Enable msg.payload : booleanfalse`
`18/11/2016, 18:34:34PIDHeat msg.payload : number59.61068`
`18/11/2016, 18:34:34PIDCOOL msg.payload : number100`
A suggestion in order to keep it simpler we can probably just use the enable / disable with the fixed value and not use the fire input.  Then disable the loop to 0 when it is in fire or the schedule is off.
- Whenever set point is reached, the PID loop output drops to 0, and this is not right as the value should go down with time (defined by Integral), otherwise setpoint will never be met and the loop will start hunting.

**Comment by hardillb** [comment]
@davidoc85 there is no enable/disable flag for the pid loop. There are only fire and fixed value. so if fire is false and fixed is false then it will continue to process temperature inputs.

I need to a have another look at the second point as I think the code that controls that was added as a direct result of the recommendations in the in the link in the first comment on this issue

**Comment by davidoc85** [comment]
You mentioned before:

> To enable fixed state you need to send a message with payload of true and to disable you need to send a value of false.

However now you are saying that there is no enable/disable fixed state function.  I think we are getting confused here.  The point that I am trying to make is that the fixed value state only sends the value once, and does not stay fixed as it should.

**Comment by hardillb** [comment]
No, I meant there is no generic disable/enable, only fire and fixed.

Anyway, I'm not seeing output after enabling fixed state here. I've just made sure the very latest version of the code is here in github. Can you pull that and give it a try. Thanks.

**Comment by davidoc85** [comment]
The PID loop doesn't seem to be working properly..
Could you update the info to explain how to send the variables properly?
I have got the current isse:
`22/11/2016, 17:56:40fixedmsg.payload : booleanfalse`
`22/11/2016, 17:56:40VHeatPIDmsg.payload : number100`
`22/11/2016, 17:56:40FSpeedResultmsg.payload : string [1]0`
`22/11/2016, 17:56:40VCoolPIDmsg.payload : number0`
`22/11/2016, 17:56:40FireInput/0 : msg.payload : booleanfalse`
`22/11/2016, 17:56:59Temptemperature : msg.payload : number22.31`
`22/11/2016, 17:56:59VHeatPIDmsg.payload : number0`
`22/11/2016, 17:56:59VCoolPIDmsg.payload : number13.099999999999987`
The output is ramiping to 100 and the goes down again. Please check my nodes, as I can't understand what is going on.  Can you please test the PID thoroughly?

test example on red-brick
[testfcu.txt](https://github.com/tyrrellsystems/node-red-contrib-pid-controller/files/607173/testfcu.txt)

Any updates on the output going to 0?  I think that was already implemented before that document.

**Comment by hardillb** [comment]
Testing is your responsibility as Ged took all testing out of scope to try and reduce costs.

I have updated the doc in the sidebar to reflect how the fixed values work.

Just posting some debug output without a description of what the inputs were really isn't helpful, and that flow you've posted is way too complex to track a problem with as it depends on a bunch of sensors I don't have set up. If you want me to look at something build a clean flow using inject nodes to show the problem so it's reproducible.

**Comment by hardillb** [comment]
I have also commented out the code that sets the output values to zero when the setpoint is reached please give it a go and see if it now does what you expect

**Comment by davidoc85** [comment]
Thanks for making the changes. I will test that later, step by step we will get there.

**Comment by hardillb** [comment]
Closing this issue to track again the new one #15
